    const toggle=document.querySelector('.toggle'),menu=document.querySelector('#menu');
    toggle?.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Fechar menu':'Abrir menu')});
    menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));

    function fozParts(){const parts=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const weekday=parts.find(p=>p.type==='weekday')?.value.toLowerCase()||'';const hour=Number(parts.find(p=>p.type==='hour')?.value||0);const minute=Number(parts.find(p=>p.type==='minute')?.value||0);const map={dom:0,seg:1,ter:2,qua:3,qui:4,sex:5,sáb:6,sab:6};const key=Object.keys(map).find(k=>weekday.startsWith(k));return{day:map[key]??new Date().getDay(),minutes:hour*60+minute}}
    function updateStatus(){const{day,minutes}=fozParts();const close=(day===5||day===6)?22*60+30:22*60;const open=9*60;const isOpen=minutes>=open&&minutes<close;const next=isOpen?`fecha às ${day===5||day===6?'22h30':'22h'}`:minutes<open?'abre às 09h':'abre amanhã às 09h';document.querySelectorAll('[data-status]').forEach(el=>el.textContent=isOpen?`Aberto agora • ${next}`:`Fechado agora • ${next}`);document.querySelectorAll('[data-status-detail]').forEach(el=>el.textContent='Horário local de Foz do Iguaçu. Confirme em feriados.');document.querySelectorAll('[data-day]').forEach(el=>el.classList.toggle('today',Number(el.dataset.day)===day))}
    updateStatus();setInterval(updateStatus,60000);

    document.querySelector('[data-copy]')?.addEventListener('click',async()=>{const text='Avenida Silvio Américo Sasdelli, 1783, sala 02, Vila A, Foz do Iguaçu - PR';const out=document.querySelector('[data-copy-feedback]');try{await navigator.clipboard.writeText(text);out.textContent='Endereço copiado.'}catch{out.textContent='Selecione o endereço acima para copiar.'}});
    document.querySelector('[data-year]').textContent=new Date().getFullYear();
    const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
